version: '3.8'
services:
  mt5-connector:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    depends_on:
      - clickhouse
    networks:
      - mt5-network

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" 
      - "9000:9000" 
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - mt5-network


networks:
  mt5-network:
    driver: bridge

volumes:
  clickhouse-data:
