version: '3.8'

services:
  data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app 
    depends_on:
      - clickhouse
    networks:
      - data-network
    command: python main.py

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  
      - "9000:9000"  
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - data-network
    restart: unless-stopped

networks:
  data-network: 
    driver: bridge

volumes:
  clickhouse-data:
    driver: local
